-- DROP DATABASE users;
-- CREATE DATABASE sipols;
-- USE sipols;
-- CREATE TABLE users (
-- id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
-- username VARCHAR(12)NOT NULL,
-- `password` VARCHAR(50)NOT NULL
-- );
-- INSERT INTO users
-- (username, `password`)
-- VALUES
-- ("slopis", "parole123");

-- SELECT * FROM users;